name: Actions Workflow

on:
  pull_request:
    branches:
      - main
    types:
      - closed
      - assigned
      - opened
      - reopened

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1